/**
 * @file port_script_addrs.c
 * AUTO-GENERATED by tools/gen_script_addrs.py — DO NOT EDIT
 *
 * Per-region translation of the baked USA script ROM addresses in
 * port_scripts.h to the matching EU/JP retail addresses, derived by exact
 * symbol lookup in the upstream zeldaret/tmc maps (see docs/MULTI_REGION.md).
 *
 * The port stores USA script addresses as compile-time constants in EntityData
 * and PORT_SCRIPT() sites. When an EU/JP ROM is loaded at runtime those USA
 * addresses point at the wrong bytecode; Port_TranslateScriptAddr() maps each
 * to the active region's address before the ROM-data resolve.
 */
#include "port_types.h"
#include "region.h"

#if defined(MULTI_REGION) || defined(EU) || defined(JP)
typedef struct { u32 usa, eu, jp; } ScriptAddrEntry;
/* Sorted by usa address for binary search. */
static const ScriptAddrEntry sScriptAddrs[] = {
    { 0x08009918, 0x080099B0, 0x08009918 }, /* script_CutsceneOrchestratorIntro */
    { 0x08009950, 0x080099E8, 0x08009950 }, /* script_SmithIntro */
    { 0x080099DC, 0x08009A74, 0x080099DC }, /* script_ZeldaIntro */
    { 0x08009A34, 0x08009ACC, 0x08009A34 }, /* script_CutsceneOrchestratorIntro2 */
    { 0x08009A50, 0x08009AE8, 0x08009A50 }, /* script_IntroCameraTarget */
    { 0x08009A84, 0x08009B1C, 0x08009A84 }, /* script_ZeldaMoveToLinksHouse */
    { 0x08009AF8, 0x08009B90, 0x08009AF8 }, /* script_HouseDoorIntro */
    { 0x08009B30, 0x08009BC8, 0x08009B30 }, /* script_PlayerIntro */
    { 0x08009D6C, 0x08009E04, 0x08009D6C }, /* script_ZeldaLeaveLinksHouse */
    { 0x08009E58, 0x08009EF0, 0x08009E58 }, /* script_PlayerWakeAfterRest */
    { 0x08009E88, 0x08009F20, 0x08009E88 }, /* script_PlayerWakingUpInHyruleCastle */
    { 0x08009ECC, 0x08009F64, 0x08009ECC }, /* script_BedInLinksRoom */
    { 0x08009EF0, 0x08009F88, 0x08009EF0 }, /* script_BedAtSimons */
    { 0x08009F14, 0x08009FAC, 0x08009F14 }, /* script_BombMinish */
    { 0x0800A0B4, 0x0800A14C, 0x0800A0B4 }, /* script_PlayerGetElement */
    { 0x0800AEDC, 0x0800AF6C, 0x0800AEDC }, /* script_CutsceneMiscObjectTheLittleHat */
    { 0x0800B0AC, 0x0800B13C, 0x0800B0AC }, /* script_EzloTalkOcarina */
    { 0x0800B41C, 0x0800B4A8, 0x0800B41C }, /* script_TalonGotKey */
    { 0x0800BA78, 0x0800BB04, 0x0800BA78 }, /* script_GormanFirstAppearance */
    { 0x0800BACC, 0x0800BB58, 0x0800BACC }, /* script_MutohKinstone */
    { 0x0800BB00, 0x0800BB8C, 0x0800BB00 }, /* script_SyrupKinstone */
    { 0x0800BB30, 0x0800BBBC, 0x0800BB30 }, /* script_BombMinishKinstone */
    { 0x0800BB64, 0x0800BBF0, 0x0800BB64 }, /* script_GoronMerchantArriving */
    { 0x0800BBA4, 0x0800BC30, 0x0800BBA4 }, /* script_StampKinstone */
    { 0x0800BBDC, 0x0800BC68, 0x0800BBDC }, /* script_CarlovKinstone */
    { 0x0800BC08, 0x0800BC94, 0x0800BC08 }, /* script_GhostBrotherKinstone */
    { 0x0800BC50, 0x0800BCDC, 0x0800BC50 }, /* script_GoronKinstone */
    { 0x0800BCE8, 0x0800BD74, 0x0800BCE8 }, /* script_Goron1Kinstone2 */
    { 0x0800BD78, 0x0800BE04, 0x0800BD78 }, /* script_Goron2Kinstone2 */
    { 0x0800BE1C, 0x0800BEA8, 0x0800BE1C }, /* script_Goron1Kinstone3 */
    { 0x0800BE54, 0x0800BEE0, 0x0800BE54 }, /* script_Goron2Kinstone3 */
    { 0x0800BECC, 0x0800BF58, 0x0800BECC }, /* script_Goron3Kinstone3 */
    { 0x0800BF38, 0x0800BFC4, 0x0800BF38 }, /* script_Goron1Kinstone4 */
    { 0x0800BF70, 0x0800BFFC, 0x0800BF70 }, /* script_Goron2Kinstone4 */
    { 0x0800C004, 0x0800C090, 0x0800C004 }, /* script_Goron4Kinstone4 */
    { 0x0800C0B0, 0x0800C13C, 0x0800C0B0 }, /* script_Goron1Kinstone5 */
    { 0x0800C0E8, 0x0800C174, 0x0800C0E8 }, /* script_Goron2Kinstone5 */
    { 0x0800C160, 0x0800C1EC, 0x0800C160 }, /* script_Goron5Kinstone5 */
    { 0x0800C1D8, 0x0800C264, 0x0800C1D8 }, /* script_Goron1Kinstone6 */
    { 0x0800C210, 0x0800C29C, 0x0800C210 }, /* script_Goron2Kinstone6 */
    { 0x0800C2A4, 0x0800C330, 0x0800C2A4 }, /* script_Goron6Kindstone6 */
    { 0x0800C350, 0x0800C3DC, 0x0800C350 }, /* script_BigGoronKinstone1 */
    { 0x0800C3CC, 0x0800C458, 0x0800C3CC }, /* script_BigGoronKinstone2 */
    { 0x0800C410, 0x0800C49C, 0x0800C410 }, /* script_BigGoronKinstone3 */
    { 0x0800C45C, 0x0800C4E8, 0x0800C45C }, /* script_KinstoneSparkKinstoneSpark */
    { 0x0800C494, 0x0800C520, 0x0800C494 }, /* script_KinstoneSparkKinstoneSparkFromBottom */
    { 0x0800C4D0, 0x0800C55C, 0x0800C4D0 }, /* script_KinstoneSparkKinstoneSparkGoronMerchang */
    { 0x0800C50C, 0x0800C598, 0x0800C50C }, /* script_KinstoneSparkKinstoneSparkGoron */
    { 0x0800C550, 0x0800C5DC, 0x0800C550 }, /* script_ForestMinish1 */
    { 0x0800C584, 0x0800C610, 0x0800C584 }, /* script_ForestMinish2 */
    { 0x0800C5C8, 0x0800C654, 0x0800C5C8 }, /* script_ForestMinish3 */
    { 0x0800C5FC, 0x0800C688, 0x0800C5FC }, /* script_ForestMinish4 */
    { 0x0800CABC, 0x0800CB48, 0x0800CABC }, /* script_ForestMinish5 */
    { 0x0800CB54, 0x0800CBE0, 0x0800CB54 }, /* script_ForestMinish6 */
    { 0x0800CBD4, 0x0800CC60, 0x0800CBD4 }, /* script_ForestMinish7 */
    { 0x0800CC6C, 0x0800CCF8, 0x0800CC6C }, /* script_ForestMinish8 */
    { 0x0800CD04, 0x0800CD90, 0x0800CD04 }, /* script_ForestMinish9 */
    { 0x0800CD7C, 0x0800CE08, 0x0800CD7C }, /* script_ForestMinish10 */
    { 0x0800DB18, 0x0800DBA4, 0x0800DB18 }, /* script_ZeldaStoneInDHC */
    { 0x0800E58C, 0x0800E624, 0x0800E598 }, /* script_ZeldaStoneDHC */
    { 0x0800E600, 0x0800E698, 0x0800E60C }, /* script_PlayerAtDarkNut1 */
    { 0x0800E62C, 0x0800E6C4, 0x0800E638 }, /* script_PlayerAtDarkNut2 */
    { 0x0800E658, 0x0800E6F0, 0x0800E664 }, /* script_PlayerAtDarkNut3 */
    { 0x0800E684, 0x0800E71C, 0x0800E690 }, /* script_PlayerAtMadderpillar */
    { 0x0800E6B0, 0x0800E748, 0x0800E6BC }, /* script_ForestMinish11 */
    { 0x0800E6E8, 0x0800E780, 0x0800E6F4 }, /* script_TownMinish1 */
    { 0x08010A5C, 0x08010AEC, 0x08010A64 }, /* script_PlayerSleepingInn */
    { 0x0801183C, 0x080118D4, 0x0801184C }, /* script_CutsceneMiscObjectSwordInChest */
    { 0x08011940, 0x080119D8, 0x08011950 }, /* script_ZeldaMagic */
    { 0x08011C50, 0x08011CE8, 0x08011C60 }, /* script_PlayerWakingUpAtSimons */
    { 0x08012C48, 0x08012CC4, 0x08012C3C }, /* script_08012C48 */
    { 0x08012DD8, 0x08012E54, 0x08012DCC }, /* script_MazaalBossObjectMazaal */
    { 0x08012E20, 0x08012E9C, 0x08012E14 }, /* script_MazaalMacroDefeated */
    { 0x08012F0C, 0x08012F88, 0x08012F00 }, /* script_Rem */
    { 0x080142B0, 0x080142E0, 0x080142A4 }, /* script_Stockwell */
    { 0x08014384, 0x080143B4, 0x08014378 }, /* script_StockwellBuy */
    { 0x080143C0, 0x080143F0, 0x080143B4 }, /* script_StockwellDogFood */
    { 0x08014A80, 0x08014AC8, 0x08014A6C }, /* script_WindTribespeople6 */
    { 0x080153EC, 0x08015434, 0x080153D8 }, /* script_CutsceneOrchestratorMinishVaati */
    { 0x0801550C, 0x08015554, 0x080154F8 }, /* script_MinishEzlo */
    { 0x08015618, 0x08015660, 0x08015604 }, /* script_CutsceneMiscObjectMinishCap */
    { 0x08015684, 0x080156CC, 0x08015670 }, /* script_Vaati */
    { 0x08015AC4, 0x08015B0C, 0x08015AB0 }, /* script_BusinessScrubIntro */
    { 0x08015B14, 0x08015B5C, 0x08015B00 }, /* script_08015B14 */
    { 0x08015CD4, 0x08015D1C, 0x08015CC0 }, /* script_CutsceneOrchestratorTakeoverCutscene */
    { 0x08015DF0, 0x08015E38, 0x08015DDC }, /* script_KingDaltusTakeover */
    { 0x08015E58, 0x08015EA0, 0x08015E44 }, /* script_VaatiTakeover */
    { 0x08015F08, 0x08015F50, 0x08015EF4 }, /* script_MinisterPothoTakeover */
    { 0x08015F3C, 0x08015F84, 0x08015F28 }, /* script_GuardTakeover */
    { 0x08015FA4, 0x08015FEC, 0x08015F90 }, /* script_ZeldaStoneTakeover */
    { 0x08016030, 0x08016078, 0x0801601C }, /* script_MinishVillageObjectLeftStoneOpening */
    { 0x0801606C, 0x080160B4, 0x08016058 }, /* script_MinishVillageObjectRightStoneOpening */
    { 0x080165F8, 0x0801663C, 0x080165E4 }, /* script_ForestMinish12 */
    { 0x0801660C, 0x08016650, 0x080165F8 }, /* script_ForestMinish13 */
    { 0x08016628, 0x0801666C, 0x08016614 }, /* script_ForestMinish14 */
    { 0x08016644, 0x08016688, 0x08016630 }, /* script_ForestMinish15 */
    { 0x0801666C, 0x080166B0, 0x08016658 }, /* script_ForestMinish16 */
    { 0x080166B8, 0x080166FC, 0x080166A4 }, /* script_ForestMinish17 */
    { 0x080166FC, 0x08016740, 0x080166E8 }, /* script_ForestMinish18 */
    { 0x08016798, 0x080167DC, 0x08016784 }, /* script_ForestMinish19 */
    { 0x08016844, 0x08016888, 0x08016830 }, /* script_ForestMinish20 */
    { 0x080168E0, 0x08016924, 0x080168CC }, /* script_ForestMinish21 */
};
#define SCRIPT_ADDR_COUNT (sizeof(sScriptAddrs) / sizeof(sScriptAddrs[0]))
#endif

/* Translate a baked USA script ROM address to the active region's address.
 * Identity for USA, for unknown addresses, and in USA single-region builds. */
u32 Port_TranslateScriptAddr(u32 usa_addr) {
#if defined(MULTI_REGION) || defined(EU) || defined(JP)
    if (REGION_IS_USA)
        return usa_addr;
    {
        int lo = 0, hi = (int)SCRIPT_ADDR_COUNT - 1;
        while (lo <= hi) {
            int mid = (lo + hi) / 2;
            u32 k = sScriptAddrs[mid].usa;
            if (k == usa_addr)
                return REGION_IS_EU ? sScriptAddrs[mid].eu : sScriptAddrs[mid].jp;
            else if (k < usa_addr)
                lo = mid + 1;
            else
                hi = mid - 1;
        }
    }
#endif
    return usa_addr;
}
