/* AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 * Generated by tools/gen_stubs.py
 */

#include "port_gba_mem.h"
#include "port_types.h"
#include <stdint.h>
#include <string.h>

/* Forward declaration for Entity* stubs */
struct Entity_;
typedef struct Entity_ Entity;

/* Area_HyruleTown -- defined in port_linked_stubs.c */

/* BounceUpdate -- implemented in port_linked_stubs.c */
/* ButtonUIElement_Actions -- defined in port_linked_stubs.c */
u32 CalcCollisionStaticEntity(...) {
    return 0;
}
/* CalcDistance -- implemented in port_math.c */
/* CalculateDirectionFromOffsets -- implemented in port_math.c */
/* CalculateDirectionTo -- implemented in port_math.c */
/* CheckBits — implemented in port_linked_stubs.c */
u32 CheckOnLayerTransition(...) {
    return 0;
}
/* CheckOnScreen -- defined in port_draw.c */
/* CheckPlayerInRegion -- implemented in port_linked_stubs.c */
u32 CheckRectOnScreen(...) {
    return 0;
}
u32 CloneTile(...) {
    return 0;
}
u32 CreateDrownFX(...) {
    return 0;
}
u32 CreateLavaDrownFX(...) {
    return 0;
}
u32 CreatePitFallFX(...) {
    return 0;
}
/* CutsceneMain_Exit -- real implementation in src/cutscene.c */
/* CutsceneMain_Init -- real implementation in src/cutscene.c */
/* CutsceneMain_Update -- real implementation in src/cutscene.c */
/* Div -- implemented in port_bios.c */
u32 DoItemTileInteraction(...) {
    return 0;
}
u32 DoTileInteraction(...) {
    return 0;
}
u32 DoTileInteractionHere(...) {
    return 0;
}
u32 DoTileInteractionOffset(...) {
    return 0;
}
/* DrawEntity -- defined in port_draw.c */
/* EEPROM functions -- defined in port_save.c */
/* Enemies_LakeHylia_Main -- defined in port_linked_stubs.c */
u32 EnemyFunctionHandler(...) {
    return 0;
}
void EnemyUpdate(Entity* entity) {
    /* Stub: enemy update not implemented yet */
}
u32 EnqueueSFX(...) {
    return 0;
}
/* Entities_HouseInteriors1_Mayor_080D6210 -- defined in port_linked_stubs.c */
/* Entities_MinishPaths_MayorsCabin_gUnk_080D6138 -- defined in port_linked_stubs.c */
/* EntityInRectRadius -- implemented in port_linked_stubs.c */
/* EzloNagUIElement_Actions -- defined in port_linked_stubs.c */
u32 FindValueForKey(...) {
    return 0;
}
u32 GenericConfused(...) {
    return 0;
}
u32 GenericKnockback(...) {
    return 0;
}
u32 GenericKnockback2(...) {
    return 0;
}
/* GetActTileAtEntity -- implemented in port_linked_stubs.c */
/* GetActTileAtRoomCoords -- implemented in port_linked_stubs.c */
/* GetActTileAtTilePos -- implemented in port_linked_stubs.c */
/* GetActTileAtWorldCoords -- implemented in port_linked_stubs.c */
/* GetActTileForTileType -- implemented in port_linked_stubs.c */
/* GetActTileRelativeToEntity -- implemented in port_linked_stubs.c */
/* GetCollisionDataAtEntity -- implemented in port_linked_stubs.c */
/* GetCollisionDataAtTilePos -- implemented in port_linked_stubs.c */
/* GetCollisionDataAtWorldCoords -- implemented in port_linked_stubs.c */
/* GetCollisionDataRelativeTo -- implemented in port_linked_stubs.c */
/* GetFacingDirection -- implemented in port_linked_stubs.c */
u32 GetFuserId(...) {
    return 0;
}
/* GetNextFrame — implemented in port_animation.c */
/* GetNextFunction — implemented in port_linked_stubs.c */
/* GetNextScriptCommandHalfword — implemented in port_stubs.c */
/* GetNextScriptCommandHalfwordAfterCommandMetadata — implemented in port_stubs.c */
/* GetNextScriptCommandWord — implemented in port_stubs.c */
/* GetNextScriptCommandWordAfterCommandMetadata — implemented in port_stubs.c */
u32 GetRandomByWeight(...) {
    return 0;
}
u32 GetTileHazardType(...) {
    return 0;
}
u32 GetTileIndex(...) {
    return 0;
}
/* GetTileTypeAtEntity -- implemented in port_linked_stubs.c */
/* GetTileTypeAtRoomCoords -- implemented in port_linked_stubs.c */
/* GetTileTypeAtTilePos -- implemented in port_linked_stubs.c */
/* GetTileTypeAtWorldCoords -- implemented in port_linked_stubs.c */
/* GetTileTypeRelativeToEntity -- implemented in port_linked_stubs.c */
/* GravityUpdate -- implemented in port_linked_stubs.c */
/* HoleManager_Actions -- defined in port_linked_stubs.c */
/* InitAnimationForceUpdate — implemented in port_animation.c */
/* InitializeAnimation — implemented in port_animation.c */
/* LinearMoveDirectionOLD — implemented in port_linked_stubs.c */
u32 LoadResourceAsync(const void* src, u32 dest, u32 size) {
    /*
     * PC port: perform the copy immediately instead of queuing for VBlank.
     * On GBA this queues into gUnk_03000C30 for later processing by LoadResources(),
     * but on PC we have no VBlank timing constraint, and queuing 64-bit native
     * pointers into the 12-byte/32-bit buffer format would truncate them.
     */
    void* resolvedDest = port_resolve_addr((uintptr_t)dest);
    if (resolvedDest && src && size > 0) {
        memcpy(resolvedDest, src, size);
    }
    return 0;
}
/* Mod — implemented in port_linked_stubs.c */
u32 PlayerCheckNEastTile(...) {
    return 0;
}
void ProjectileUpdate(Entity* entity) {
    /* Stub: projectile update not implemented yet */
}
/* RAMFUNCS_END -- defined in port_linked_stubs.c */
/* Random — implemented in port_linked_stubs.c */
u32 ResetCollisionLayer(...) {
    return 0;
}
u32 ResolveCollisionLayer(...) {
    return 0;
}
/* RupeeKeyDigits -- defined in port_linked_stubs.c */
u32 SetActTileAtTilePos(...) {
    return 0;
}
u32 SetCollisionData(...) {
    return 0;
}
u32 SetTile(...) {
    return 0;
}
u32 SnapToTile(...) {
    return 0;
}
u32 SoundReqClipped(...) {
    return 0;
}
/* Subtask_FastTravel_Functions -- defined in port_linked_stubs.c */
/* Subtask_MapHint_Functions -- defined in port_linked_stubs.c */
/* SumDropProbabilities — implemented in port_linked_stubs.c */
/* SumDropProbabilities2 — implemented in port_linked_stubs.c */
/* UnpackTextNibbles — implemented in port_text_render.c */
/* UpdateAnimationSingleFrame — implemented in port_animation.c */
/* UpdateAnimationVariableFrames — implemented in port_animation.c */
void UpdateCollision(Entity* entity) {
    /* Stub: collision handling not implemented yet */
}
u32 UpdateCollisionLayer(...) {
    return 0;
}
u32 UpdateIcePlayerVelocity(...) {
    return 0;
}
/* UpdateScrollVram — implemented in port_linked_stubs.c */
/* UpdateSpriteForCollisionLayer — implemented in port_linked_stubs.c */
/* UpperInn_Din -- defined in port_linked_stubs.c */
/* UpperInn_Farore -- defined in port_linked_stubs.c */
/* UpperInn_Nayru -- defined in port_linked_stubs.c */
/* UpperInn_NoDin -- defined in port_linked_stubs.c */
/* UpperInn_NoFarore -- defined in port_linked_stubs.c */
/* UpperInn_NoNayru -- defined in port_linked_stubs.c */
/* UpperInn_Oracles -- defined in port_linked_stubs.c */
u32 WorldEvent_0(...) {
    return 0;
}
u32 WorldEvent_1(...) {
    return 0;
}
u32 WorldEvent_11(...) {
    return 0;
}
u32 WorldEvent_12(...) {
    return 0;
}
u32 WorldEvent_13(...) {
    return 0;
}
u32 WorldEvent_14(...) {
    return 0;
}
u32 WorldEvent_15(...) {
    return 0;
}
u32 WorldEvent_16(...) {
    return 0;
}
u32 WorldEvent_17(...) {
    return 0;
}
u32 WorldEvent_19(...) {
    return 0;
}
u32 WorldEvent_2(...) {
    return 0;
}
u32 WorldEvent_20(...) {
    return 0;
}
u32 WorldEvent_21(...) {
    return 0;
}
u32 WorldEvent_22(...) {
    return 0;
}
u32 WorldEvent_23(...) {
    return 0;
}
u32 WorldEvent_24(...) {
    return 0;
}
u32 WorldEvent_25(...) {
    return 0;
}
u32 WorldEvent_3(...) {
    return 0;
}
u32 WorldEvent_4(...) {
    return 0;
}
u32 WorldEvent_5(...) {
    return 0;
}
u32 WorldEvent_6(...) {
    return 0;
}
u32 WorldEvent_7(...) {
    return 0;
}
u32 WorldEvent_8(...) {
    return 0;
}
u32 WorldEvent_9(...) {
    return 0;
}
u32 WorldEvent_Beanstalk(...) {
    return 0;
}
/* bgmBeanstalk -- defined in port_linked_stubs.c */
/* bgmBeatVaati -- defined in port_linked_stubs.c */
/* bgmBossTheme -- defined in port_linked_stubs.c */
/* bgmCastleCollapse -- defined in port_linked_stubs.c */
/* bgmCastleMotif -- defined in port_linked_stubs.c */
/* bgmCastleTournament -- defined in port_linked_stubs.c */
/* bgmCastorWilds -- defined in port_linked_stubs.c */
/* bgmCaveOfFlames -- defined in port_linked_stubs.c */
/* bgmCloudTops -- defined in port_linked_stubs.c */
/* bgmCredits -- defined in port_linked_stubs.c */
/* bgmCrenelStorm -- defined in port_linked_stubs.c */
/* bgmCuccoMinigame -- defined in port_linked_stubs.c */
/* bgmDarkHyruleCastle -- defined in port_linked_stubs.c */
/* bgmDeepwoodShrine -- defined in port_linked_stubs.c */
/* bgmDiggingCave -- defined in port_linked_stubs.c */
/* bgmDungeon -- defined in port_linked_stubs.c */
/* bgmElementGet -- defined in port_linked_stubs.c */
/* bgmElementTheme -- defined in port_linked_stubs.c */
/* bgmElementalSanctuary -- defined in port_linked_stubs.c */
/* bgmEzloGet -- defined in port_linked_stubs.c */
/* bgmEzloStory -- defined in port_linked_stubs.c */
/* bgmEzloTheme -- defined in port_linked_stubs.c */
/* bgmFairyFountain -- defined in port_linked_stubs.c */
/* bgmFairyFountain2 -- defined in port_linked_stubs.c */
/* bgmFestivalApproach -- defined in port_linked_stubs.c */
/* bgmFightTheme -- defined in port_linked_stubs.c */
/* bgmFightTheme2 -- defined in port_linked_stubs.c */
/* bgmFileSelect -- defined in port_linked_stubs.c */
/* bgmFortressOfWinds -- defined in port_linked_stubs.c */
/* bgmGameover -- defined in port_linked_stubs.c */
/* bgmHouse -- defined in port_linked_stubs.c */
/* bgmHyruleCastle -- defined in port_linked_stubs.c */
/* bgmHyruleCastleNointro -- defined in port_linked_stubs.c */
/* bgmHyruleField -- defined in port_linked_stubs.c */
/* bgmHyruleTown -- defined in port_linked_stubs.c */
/* bgmIntroCutscene -- defined in port_linked_stubs.c */
/* bgmLearnScroll -- defined in port_linked_stubs.c */
/* bgmLostWoods -- defined in port_linked_stubs.c */
/* bgmLttpTitle -- defined in port_linked_stubs.c */
/* bgmMinishCap -- defined in port_linked_stubs.c */
/* bgmMinishVillage -- defined in port_linked_stubs.c */
/* bgmMinishWoods -- defined in port_linked_stubs.c */
/* bgmMtCrenel -- defined in port_linked_stubs.c */
/* bgmPalaceOfWinds -- defined in port_linked_stubs.c */
/* bgmPicoriFestival -- defined in port_linked_stubs.c */
/* bgmRoyalCrypt -- defined in port_linked_stubs.c */
/* bgmRoyalValley -- defined in port_linked_stubs.c */
/* bgmSavingZelda -- defined in port_linked_stubs.c */
/* bgmSecretCastleEntrance -- defined in port_linked_stubs.c */
/* bgmStory -- defined in port_linked_stubs.c */
/* bgmSwiftbladeDojo -- defined in port_linked_stubs.c */
/* bgmSyrupTheme -- defined in port_linked_stubs.c */
/* bgmTempleOfDroplets -- defined in port_linked_stubs.c */
/* bgmTitleScreen -- defined in port_linked_stubs.c */
/* bgmUnused -- defined in port_linked_stubs.c */
/* bgmVaatiMotif -- defined in port_linked_stubs.c */
/* bgmVaatiReborn -- defined in port_linked_stubs.c */
/* bgmVaatiTheme -- defined in port_linked_stubs.c */
/* bgmVaatiTransfigured -- defined in port_linked_stubs.c */
/* bgmVaatiWrath -- defined in port_linked_stubs.c */
/* bgmWindRuins -- defined in port_linked_stubs.c */
/* gAreaMetadata -- defined in port_linked_stubs.c */
/* gAreaRoomHeaders -- defined in port_linked_stubs.c */
/* gAreaRoomMaps -- defined in port_linked_stubs.c */
/* gAreaTable -- defined in port_linked_stubs.c */
/* gAreaTileSets -- defined in port_linked_stubs.c */
/* gAreaTiles -- defined in port_linked_stubs.c */

/* gCaveBorderMapData -- defined in port_linked_stubs.c */
/* gChooseFileState — defined in port_linked_stubs.c */
/* gCollidableCount — defined in port_linked_stubs.c */
/* gCollisionMtx — defined in port_linked_stubs.c */
/* gCopyToEndOfEwram_End -- defined in port_linked_stubs.c */
/* gCopyToEndOfEwram_Start -- defined in port_linked_stubs.c */

/* gDiggingCaveEntranceTransition -- defined in port_linked_stubs.c */
/* gDungeonMap -- defined in port_linked_stubs.c */
/* gDungeonNames -- defined in port_linked_stubs.c */
/* gEndOfEwram -- defined in port_linked_stubs.c */

/* gExitList_RoyalValley_ForestMaze -- defined in port_linked_stubs.c */
/* gExitLists -- defined in port_linked_stubs.c */
/* gExtraFrameOffsets -- defined in port_linked_stubs.c */
/* gFigurines -- defined in port_linked_stubs.c */
/* gFixedTypeGfxData -- defined in port_linked_stubs.c */

/* gFuseInfo -- defined in port_linked_stubs.c */
/* gHitbox_0 -- defined in port_linked_stubs.c */
/* gHitbox_1 -- defined in port_linked_stubs.c */
/* gHitbox_10 -- defined in port_linked_stubs.c */
/* gHitbox_11 -- defined in port_linked_stubs.c */
/* gHitbox_12 -- defined in port_linked_stubs.c */
/* gHitbox_13 -- defined in port_linked_stubs.c */
/* gHitbox_14 -- defined in port_linked_stubs.c */
/* gHitbox_15 -- defined in port_linked_stubs.c */
/* gHitbox_16 -- defined in port_linked_stubs.c */
/* gHitbox_17 -- defined in port_linked_stubs.c */
/* gHitbox_18 -- defined in port_linked_stubs.c */
/* gHitbox_19 -- defined in port_linked_stubs.c */
/* gHitbox_2 -- defined in port_linked_stubs.c */
/* gHitbox_20 -- defined in port_linked_stubs.c */
/* gHitbox_21 -- defined in port_linked_stubs.c */
/* gHitbox_22 -- defined in port_linked_stubs.c */
/* gHitbox_23 -- defined in port_linked_stubs.c */
/* gHitbox_24 -- defined in port_linked_stubs.c */
/* gHitbox_25 -- defined in port_linked_stubs.c */
/* gHitbox_26 -- defined in port_linked_stubs.c */
/* gHitbox_27 -- defined in port_linked_stubs.c */
/* gHitbox_28 -- defined in port_linked_stubs.c */
/* gHitbox_29 -- defined in port_linked_stubs.c */
/* gHitbox_3 -- defined in port_linked_stubs.c */
/* gHitbox_30 -- defined in port_linked_stubs.c */
/* gHitbox_31 -- defined in port_linked_stubs.c */
/* gHitbox_32 -- defined in port_linked_stubs.c */
/* gHitbox_4 -- defined in port_linked_stubs.c */
/* gHitbox_5 -- defined in port_linked_stubs.c */
/* gHitbox_6 -- defined in port_linked_stubs.c */
/* gHitbox_7 -- defined in port_linked_stubs.c */
/* gHitbox_8 -- defined in port_linked_stubs.c */
/* gHitbox_9 -- defined in port_linked_stubs.c */

/* gLilypadRails -- defined in port_linked_stubs.c */
/* gMPlayInfos -- defined in port_linked_stubs.c */
/* gMPlayInfos2 -- defined in port_linked_stubs.c */
/* gMPlayTracks -- defined in port_linked_stubs.c */

/* gManagerCount — defined in port_linked_stubs.c */
/* gMapActTileToSurfaceType -- defined in port_linked_stubs.c */
/* gMapBottom — defined in port_linked_stubs.c */
/* gMapData — defined in port_linked_stubs.c */
/* gMapDataBottomSpecial -- defined in port_linked_stubs.c */
/* gMapDataTopSpecial -- defined in port_linked_stubs.c */
/* gMapTop — defined in port_linked_stubs.c */
/* gMenu — defined in port_linked_stubs.c */
/* gMessageChoices -- defined in port_linked_stubs.c */
/* gMoreSpritePtrs -- defined in port_linked_stubs.c */
/* gNPCData -- defined in port_linked_stubs.c */
/* gOverworldLocations -- defined in port_linked_stubs.c */
/* gPaletteBufferBackup — defined in port_linked_stubs.c */
/* gPaletteList -- defined in port_linked_stubs.c */
/* gPalette_549 -- defined in port_linked_stubs.c */
/* gPauseMenuOptions -- defined in port_linked_stubs.c */
/* gPlayerClones — defined in port_linked_stubs.c */
/* gPlayerEntity — defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers0 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers1 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers2 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers3 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers4 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers5 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers6 -- defined in port_linked_stubs.c */
/* gPlayerMacroBladeBrothers7 -- defined in port_linked_stubs.c */
/* gPlayerScriptExecutionContext — defined in port_linked_stubs.c */
/* gPlayerState — defined in port_linked_stubs.c */
/* gPossibleInteraction — defined in port_linked_stubs.c */
/* gPriorityHandler — defined in port_linked_stubs.c */
/* gRoomControls — defined in port_linked_stubs.c */
/* gRoomMemory — defined in port_linked_stubs.c */
/* gRoomTransition — defined in port_linked_stubs.c */
/* gRoomVars — defined in port_linked_stubs.c */
/* gSave — defined in port_linked_stubs.c */
/* gScriptExecutionContextArray — defined in port_linked_stubs.c */
/* gShakeOffsets -- defined in port_linked_stubs.c */
/* gSmallChests -- defined in port_linked_stubs.c */
/* gSpriteAnimations_322 -- defined in port_linked_stubs.c */
/* gSpriteAnimations_GhostBrothers -- defined in port_linked_stubs.c */
/* gSpritePtrs -- defined in port_linked_stubs.c */
/* gSubtasks -- defined in port_linked_stubs.c */
/* gTextGfxBuffer — defined in port_linked_stubs.c */
/* gTilesForSpecialTiles -- defined in port_linked_stubs.c */
/* gTranslations -- defined in port_linked_stubs.c */
/* gUI — defined in port_linked_stubs.c */
/* gUIElementDefinitions -- defined in port_linked_stubs.c */
/* gUnk_03000420 -- defined in port_linked_stubs.c */
/* gUnk_03000C30 -- defined in port_linked_stubs.c */
/* gUnk_03001020 -- defined in port_linked_stubs.c */
/* gUnk_03003C70 -- defined in port_linked_stubs.c */
u8 gUnk_03003DE0;
u8 gUnk_03003DE4[0xC];
/* gUnk_additional_8_DeepwoodShrine_StairsToB1 -- defined in port_linked_stubs.c */
/* gUnk_additional_8_HouseInteriors1_Library1F -- defined in port_linked_stubs.c */
/* gUnk_additional_8_HouseInteriors3_BorlovEntrance -- defined in port_linked_stubs.c */
/* gUnk_additional_8_HyruleCastle_3 -- defined in port_linked_stubs.c */
/* gUnk_additional_8_MelarisMine_Main -- defined in port_linked_stubs.c */
/* gUnk_additional_8_PalaceOfWinds_GyorgTornado -- defined in port_linked_stubs.c */
/* gUnk_additional_9_HouseInteriors1_Library1F -- defined in port_linked_stubs.c */
/* gUnk_additional_9_HouseInteriors2_Percy -- defined in port_linked_stubs.c */
/* gUnk_additional_9_HouseInteriors3_BorlovEntrance -- defined in port_linked_stubs.c */
/* gUnk_additional_9_MelarisMine_Main -- defined in port_linked_stubs.c */
/* gUnk_additional_9_PalaceOfWinds_GyorgTornado -- defined in port_linked_stubs.c */
/* gUnk_additional_a_CaveOfFlamesBoss_Main -- defined in port_linked_stubs.c */
/* gUnk_additional_a_DeepwoodShrineBoss_Main -- defined in port_linked_stubs.c */
/* gUnk_additional_a_HouseInteriors2_Percy -- defined in port_linked_stubs.c */
/* gUnk_additional_a_HouseInteriors3_BorlovEntrance -- defined in port_linked_stubs.c */
/* gUnk_additional_a_TempleOfDroplets_BigOcto -- defined in port_linked_stubs.c */
/* gUnk_additional_c_HouseInteriors2_Romio -- defined in port_linked_stubs.c */
/* gUpdateContext — defined in port_linked_stubs.c */
/* gUpdateVisibleTiles — defined in port_linked_stubs.c */
/* gVBlankDMA — defined in port_linked_stubs.c */
/* gWallMasterScreenTransitions -- defined in port_linked_stubs.c */
/* gZeldaFollowerText -- defined in port_linked_stubs.c */
/* gzHeap -- defined in port_linked_stubs.c */
u32 m4aMPlayAllStop(...) {
    return 0;
}
u32 m4aMPlayImmInit(...) {
    return 0;
}
u32 m4aMPlayTempoControl(...) {
    return 0;
}
u32 m4aMPlayVolumeControl(...) {
    return 0;
}
u32 m4aSongNumStart(...) {
    return 0;
}
u32 m4aSongNumStartOrContinue(...) {
    return 0;
}
u32 m4aSongNumStop(...) {
    return 0;
}
u32 m4aSoundInit(...) {
    return 0;
}
u32 m4aSoundMain(...) {
    return 0;
}
u32 m4aSoundVSync(...) {
    return 0;
}
u32 m4aSoundVSyncOff(...) {
    return 0;
}
u32 m4aSoundVSyncOn(...) {
    return 0;
}
/* ram_ClearAndUpdateEntities -- defined in port_draw.c */
u32 ram_CollideAll(...) {
    return 0;
}
/* ram_DrawDirect -- defined in port_draw.c */
/* ram_DrawEntities -- defined in port_draw.c */
u32 ram_IntrMain(...) {
    return 0;
}
/* ram_MakeFadeBuff256 -- defined in port_linked_stubs.c */
/* ram_UpdateEntities -- defined in port_draw.c */
/* ram_sub_080ADA04 -- defined in port_draw.c */
/* ram_sub_080B197C -- defined in port_linked_stubs.c */
/* script_08012C48 -- defined in port_linked_stubs.c */
/* script_08015B14 -- defined in port_linked_stubs.c */
/* script_BedAtSimons -- defined in port_linked_stubs.c */
/* script_BedInLinksRoom -- defined in port_linked_stubs.c */
/* script_BombMinish -- defined in port_linked_stubs.c */
/* script_BombMinishKinstone -- defined in port_linked_stubs.c */
/* script_BusinessScrubIntro -- defined in port_linked_stubs.c */
/* script_CutsceneMiscObjectSwordInChest -- defined in port_linked_stubs.c */
/* script_CutsceneMiscObjectTheLittleHat -- defined in port_linked_stubs.c */
/* script_EzloTalkOcarina -- defined in port_linked_stubs.c */
/* script_ForestMinish1 -- defined in port_linked_stubs.c */
/* script_ForestMinish10 -- defined in port_linked_stubs.c */
/* script_ForestMinish11 -- defined in port_linked_stubs.c */
/* script_ForestMinish12 -- defined in port_linked_stubs.c */
/* script_ForestMinish13 -- defined in port_linked_stubs.c */
/* script_ForestMinish14 -- defined in port_linked_stubs.c */
/* script_ForestMinish15 -- defined in port_linked_stubs.c */
/* script_ForestMinish16 -- defined in port_linked_stubs.c */
/* script_ForestMinish17 -- defined in port_linked_stubs.c */
/* script_ForestMinish18 -- defined in port_linked_stubs.c */
/* script_ForestMinish19 -- defined in port_linked_stubs.c */
/* script_ForestMinish2 -- defined in port_linked_stubs.c */
/* script_ForestMinish20 -- defined in port_linked_stubs.c */
/* script_ForestMinish21 -- defined in port_linked_stubs.c */
/* script_ForestMinish3 -- defined in port_linked_stubs.c */
/* script_ForestMinish4 -- defined in port_linked_stubs.c */
/* script_ForestMinish5 -- defined in port_linked_stubs.c */
/* script_ForestMinish6 -- defined in port_linked_stubs.c */
/* script_ForestMinish7 -- defined in port_linked_stubs.c */
/* script_ForestMinish8 -- defined in port_linked_stubs.c */
/* script_ForestMinish9 -- defined in port_linked_stubs.c */
/* script_MazaalBossObjectMazaal -- defined in port_linked_stubs.c */
/* script_MazaalMacroDefeated -- defined in port_linked_stubs.c */
/* script_MinishVillageObjectLeftStoneOpening -- defined in port_linked_stubs.c */
/* script_MinishVillageObjectRightStoneOpening -- defined in port_linked_stubs.c */
/* script_PlayerAtDarkNut1 -- defined in port_linked_stubs.c */
/* script_PlayerAtDarkNut2 -- defined in port_linked_stubs.c */
/* script_PlayerAtDarkNut3 -- defined in port_linked_stubs.c */
/* script_PlayerAtMadderpillar -- defined in port_linked_stubs.c */
/* script_PlayerGetElement -- defined in port_linked_stubs.c */
/* script_PlayerIntro -- defined in port_linked_stubs.c */
/* script_PlayerSleepingInn -- defined in port_linked_stubs.c */
/* script_PlayerWakeAfterRest -- defined in port_linked_stubs.c */
/* script_PlayerWakingUpAtSimons -- defined in port_linked_stubs.c */
/* script_PlayerWakingUpInHyruleCastle -- defined in port_linked_stubs.c */
/* script_Rem -- defined in port_linked_stubs.c */
/* script_Stockwell -- defined in port_linked_stubs.c */
/* script_StockwellBuy -- defined in port_linked_stubs.c */
/* script_StockwellDogFood -- defined in port_linked_stubs.c */
/* script_TalonGotKey -- defined in port_linked_stubs.c */
/* script_WindTribespeople6 -- defined in port_linked_stubs.c */
/* script_ZeldaMagic -- defined in port_linked_stubs.c */
u32 sub_08000E44(...) {
    return 0;
}
u32 sub_08000E62(...) {
    return 0;
}
u32 sub_08001290(...) {
    return 0;
}
u32 sub_080012DC(...) {
    return 0;
}
u32 sub_08001318(...) {
    return 0;
}
u32 sub_0800132C(...) {
    return 0;
}
/* sub_080026C4 — implemented in port_text_render.c */
/* sub_080026F2 — implemented in port_text_render.c */
u32 sub_080028E0(...) {
    return 0;
}
u32 sub_08003FDE(...) {
    return 0;
}
u32 sub_080040A2(...) {
    return 0;
}
u32 sub_080040D8(...) {
    return 0;
}
u32 sub_080040E2(...) {
    return 0;
}
u32 sub_0800417E(...) {
    return 0;
}
u32 sub_0800419C(...) {
    return 0;
}
u32 sub_080041DC(...) {
    return 0;
}
u32 sub_080041E8(...) {
    return 0;
}
u32 sub_08004202(...) {
    return 0;
}
/* sub_080042BA — implemented in port_animation.c */
/* sub_080042D0 — implemented in port_animation.c */
u32 sub_0800442E(...) {
    return 0;
}
u32 sub_0800445C(...) {
    return 0;
}
u32 sub_080044AE(...) {
    return 0;
}
u32 sub_0800451C(...) {
    return 0;
}
u32 sub_08004542(...) {
    return 0;
}
u32 sub_08004596(...) {
    return 0;
}
/* sub_080045B4 — implemented in port_linked_stubs.c */
/* sub_0800857C — implemented in port_linked_stubs.c */
/* sub_080085B0 — implemented in port_linked_stubs.c */
u32 sub_080086B4(...) {
    return 0;
}
u32 sub_08008926(...) {
    return 0;
}
/* sub_08008AA0 — implemented in port_linked_stubs.c */
/* sub_08008AC6 — implemented in port_linked_stubs.c */
/* sub_080B197C -- defined in port_linked_stubs.c */
/* sub_080B1B84 -- implemented in port_linked_stubs.c */
/* sub_080B1BA4 -- implemented in port_linked_stubs.c */
