/* AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 * Generated by tools/gen_stubs.py
 */

#include "port_types.h"
#include <stdint.h>

/*
 * Varargs stubs avoid ABI/signature issues during early porting.
 * Replace progressively with real prototypes/implementations.
 */

u32 Area_HyruleTown(...) {
    return 0;
}
u32 BgAffineSet(...) {
    return 0;
}
u32 BounceUpdate(...) {
    return 0;
}
u32 ButtonUIElement_Actions(...) {
    return 0;
}
u32 CalcCollisionStaticEntity(...) {
    return 0;
}
u32 CalcDistance(...) {
    return 0;
}
u32 CalculateDirectionFromOffsets(...) {
    return 0;
}
u32 CalculateDirectionTo(...) {
    return 0;
}
u32 CheckBits(...) {
    return 0;
}
u32 CheckOnLayerTransition(...) {
    return 0;
}
u32 CheckOnScreen(...) {
    return 0;
}
u32 CheckPlayerInRegion(...) {
    return 0;
}
u32 CheckRectOnScreen(...) {
    return 0;
}
u32 CloneTile(...) {
    return 0;
}
u32 CpuSet(...) {
    return 0;
}
u32 CreateDrownFX(...) {
    return 0;
}
u32 CreateLavaDrownFX(...) {
    return 0;
}
u32 CreatePitFallFX(...) {
    return 0;
}
u32 CutsceneMain_Exit(...) {
    return 0;
}
u32 CutsceneMain_Init(...) {
    return 0;
}
u32 CutsceneMain_Update(...) {
    return 0;
}
u32 Div(...) {
    return 0;
}
u32 DoItemTileInteraction(...) {
    return 0;
}
u32 DoTileInteraction(...) {
    return 0;
}
u32 DoTileInteractionHere(...) {
    return 0;
}
u32 DoTileInteractionOffset(...) {
    return 0;
}
u32 DrawEntity(...) {
    return 0;
}
u32 EEPROMCompare(...) {
    return 0;
}
u32 EEPROMConfigure(...) {
    return 0;
}
u32 EEPROMRead(...) {
    return 0;
}
u32 EEPROMWrite0_8k_Check(...) {
    return 0;
}
u32 Enemies_LakeHylia_Main(...) {
    return 0;
}
u32 EnemyFunctionHandler(...) {
    return 0;
}
u32 EnqueueSFX(...) {
    return 0;
}
u32 Entities_HouseInteriors1_Mayor_080D6210(...) {
    return 0;
}
u32 Entities_MinishPaths_MayorsCabin_gUnk_080D6138(...) {
    return 0;
}
u32 EntityInRectRadius(...) {
    return 0;
}
u32 EzloNagUIElement_Actions(...) {
    return 0;
}
u32 FindValueForKey(...) {
    return 0;
}
u32 GenericConfused(...) {
    return 0;
}
u32 GenericKnockback(...) {
    return 0;
}
u32 GenericKnockback2(...) {
    return 0;
}
u32 GetActTileAtEntity(...) {
    return 0;
}
u32 GetActTileAtRoomCoords(...) {
    return 0;
}
u32 GetActTileAtTilePos(...) {
    return 0;
}
u32 GetActTileAtWorldCoords(...) {
    return 0;
}
u32 GetActTileForTileType(...) {
    return 0;
}
u32 GetActTileRelativeToEntity(...) {
    return 0;
}
u32 GetCollisionDataAtEntity(...) {
    return 0;
}
u32 GetCollisionDataAtTilePos(...) {
    return 0;
}
u32 GetCollisionDataAtWorldCoords(...) {
    return 0;
}
u32 GetCollisionDataRelativeTo(...) {
    return 0;
}
u32 GetFacingDirection(...) {
    return 0;
}
u32 GetFuserId(...) {
    return 0;
}
u32 GetNextFrame(...) {
    return 0;
}
u32 GetNextFunction(...) {
    return 0;
}
u32 GetNextScriptCommandHalfword(...) {
    return 0;
}
u32 GetNextScriptCommandHalfwordAfterCommandMetadata(...) {
    return 0;
}
u32 GetNextScriptCommandWord(...) {
    return 0;
}
u32 GetNextScriptCommandWordAfterCommandMetadata(...) {
    return 0;
}
u32 GetRandomByWeight(...) {
    return 0;
}
u32 GetTileHazardType(...) {
    return 0;
}
u32 GetTileIndex(...) {
    return 0;
}
u32 GetTileTypeAtEntity(...) {
    return 0;
}
u32 GetTileTypeAtRoomCoords(...) {
    return 0;
}
u32 GetTileTypeAtTilePos(...) {
    return 0;
}
u32 GetTileTypeAtWorldCoords(...) {
    return 0;
}
u32 GetTileTypeRelativeToEntity(...) {
    return 0;
}
u32 GravityUpdate(...) {
    return 0;
}
u32 HoleManager_Actions(...) {
    return 0;
}
u32 InitAnimationForceUpdate(...) {
    return 0;
}
u32 InitializeAnimation(...) {
    return 0;
}
u32 LZ77UnCompVram(...) {
    return 0;
}
u32 LZ77UnCompWram(...) {
    return 0;
}
u32 LinearMoveDirectionOLD(...) {
    return 0;
}
u32 LoadResourceAsync(...) {
    return 0;
}
u32 Mod(...) {
    return 0;
}
u32 ObjAffineSet(...) {
    return 0;
}
u32 PlayerCheckNEastTile(...) {
    return 0;
}
u32 RAMFUNCS_END(...) {
    return 0;
}
u32 Random(...) {
    return 0;
}
u32 RegisterRamReset(...) {
    return 0;
}
u32 ResetCollisionLayer(...) {
    return 0;
}
u32 ResolveCollisionLayer(...) {
    return 0;
}
u32 RupeeKeyDigits(...) {
    return 0;
}
u32 SetActTileAtTilePos(...) {
    return 0;
}
u32 SetCollisionData(...) {
    return 0;
}
u32 SetTile(...) {
    return 0;
}
u32 SnapToTile(...) {
    return 0;
}
u32 SoftReset(...) {
    return 0;
}
u32 SoundReqClipped(...) {
    return 0;
}
u32 Subtask_FastTravel_Functions(...) {
    return 0;
}
u32 Subtask_MapHint_Functions(...) {
    return 0;
}
u32 SumDropProbabilities(...) {
    return 0;
}
u32 SumDropProbabilities2(...) {
    return 0;
}
u32 UnpackTextNibbles(...) {
    return 0;
}
u32 UpdateAnimationSingleFrame(...) {
    return 0;
}
u32 UpdateAnimationVariableFrames(...) {
    return 0;
}
u32 UpdateCollisionLayer(...) {
    return 0;
}
u32 UpdateIcePlayerVelocity(...) {
    return 0;
}
u32 UpdateScrollVram(...) {
    return 0;
}
u32 UpdateSpriteForCollisionLayer(...) {
    return 0;
}
u32 UpperInn_Din(...) {
    return 0;
}
u32 UpperInn_Farore(...) {
    return 0;
}
u32 UpperInn_Nayru(...) {
    return 0;
}
u32 UpperInn_NoDin(...) {
    return 0;
}
u32 UpperInn_NoFarore(...) {
    return 0;
}
u32 UpperInn_NoNayru(...) {
    return 0;
}
u32 UpperInn_Oracles(...) {
    return 0;
}
u32 WorldEvent_0(...) {
    return 0;
}
u32 WorldEvent_1(...) {
    return 0;
}
u32 WorldEvent_11(...) {
    return 0;
}
u32 WorldEvent_12(...) {
    return 0;
}
u32 WorldEvent_13(...) {
    return 0;
}
u32 WorldEvent_14(...) {
    return 0;
}
u32 WorldEvent_15(...) {
    return 0;
}
u32 WorldEvent_16(...) {
    return 0;
}
u32 WorldEvent_17(...) {
    return 0;
}
u32 WorldEvent_19(...) {
    return 0;
}
u32 WorldEvent_2(...) {
    return 0;
}
u32 WorldEvent_20(...) {
    return 0;
}
u32 WorldEvent_21(...) {
    return 0;
}
u32 WorldEvent_22(...) {
    return 0;
}
u32 WorldEvent_23(...) {
    return 0;
}
u32 WorldEvent_24(...) {
    return 0;
}
u32 WorldEvent_25(...) {
    return 0;
}
u32 WorldEvent_3(...) {
    return 0;
}
u32 WorldEvent_4(...) {
    return 0;
}
u32 WorldEvent_5(...) {
    return 0;
}
u32 WorldEvent_6(...) {
    return 0;
}
u32 WorldEvent_7(...) {
    return 0;
}
u32 WorldEvent_8(...) {
    return 0;
}
u32 WorldEvent_9(...) {
    return 0;
}
u32 WorldEvent_Beanstalk(...) {
    return 0;
}
u32 bgmBeanstalk(...) {
    return 0;
}
u32 bgmBeatVaati(...) {
    return 0;
}
u32 bgmBossTheme(...) {
    return 0;
}
u32 bgmCastleCollapse(...) {
    return 0;
}
u32 bgmCastleMotif(...) {
    return 0;
}
u32 bgmCastleTournament(...) {
    return 0;
}
u32 bgmCastorWilds(...) {
    return 0;
}
u32 bgmCaveOfFlames(...) {
    return 0;
}
u32 bgmCloudTops(...) {
    return 0;
}
u32 bgmCredits(...) {
    return 0;
}
u32 bgmCrenelStorm(...) {
    return 0;
}
u32 bgmCuccoMinigame(...) {
    return 0;
}
u32 bgmDarkHyruleCastle(...) {
    return 0;
}
u32 bgmDeepwoodShrine(...) {
    return 0;
}
u32 bgmDiggingCave(...) {
    return 0;
}
u32 bgmDungeon(...) {
    return 0;
}
u32 bgmElementGet(...) {
    return 0;
}
u32 bgmElementTheme(...) {
    return 0;
}
u32 bgmElementalSanctuary(...) {
    return 0;
}
u32 bgmEzloGet(...) {
    return 0;
}
u32 bgmEzloStory(...) {
    return 0;
}
u32 bgmEzloTheme(...) {
    return 0;
}
u32 bgmFairyFountain(...) {
    return 0;
}
u32 bgmFairyFountain2(...) {
    return 0;
}
u32 bgmFestivalApproach(...) {
    return 0;
}
u32 bgmFightTheme(...) {
    return 0;
}
u32 bgmFightTheme2(...) {
    return 0;
}
u32 bgmFileSelect(...) {
    return 0;
}
u32 bgmFortressOfWinds(...) {
    return 0;
}
u32 bgmGameover(...) {
    return 0;
}
u32 bgmHouse(...) {
    return 0;
}
u32 bgmHyruleCastle(...) {
    return 0;
}
u32 bgmHyruleCastleNointro(...) {
    return 0;
}
u32 bgmHyruleField(...) {
    return 0;
}
u32 bgmHyruleTown(...) {
    return 0;
}
u32 bgmIntroCutscene(...) {
    return 0;
}
u32 bgmLearnScroll(...) {
    return 0;
}
u32 bgmLostWoods(...) {
    return 0;
}
u32 bgmLttpTitle(...) {
    return 0;
}
u32 bgmMinishCap(...) {
    return 0;
}
u32 bgmMinishVillage(...) {
    return 0;
}
u32 bgmMinishWoods(...) {
    return 0;
}
u32 bgmMtCrenel(...) {
    return 0;
}
u32 bgmPalaceOfWinds(...) {
    return 0;
}
u32 bgmPicoriFestival(...) {
    return 0;
}
u32 bgmRoyalCrypt(...) {
    return 0;
}
u32 bgmRoyalValley(...) {
    return 0;
}
u32 bgmSavingZelda(...) {
    return 0;
}
u32 bgmSecretCastleEntrance(...) {
    return 0;
}
u32 bgmStory(...) {
    return 0;
}
u32 bgmSwiftbladeDojo(...) {
    return 0;
}
u32 bgmSyrupTheme(...) {
    return 0;
}
u32 bgmTempleOfDroplets(...) {
    return 0;
}
u32 bgmTitleScreen(...) {
    return 0;
}
u32 bgmUnused(...) {
    return 0;
}
u32 bgmVaatiMotif(...) {
    return 0;
}
u32 bgmVaatiReborn(...) {
    return 0;
}
u32 bgmVaatiTheme(...) {
    return 0;
}
u32 bgmVaatiTransfigured(...) {
    return 0;
}
u32 bgmVaatiWrath(...) {
    return 0;
}
u32 bgmWindRuins(...) {
    return 0;
}
u32 gActiveItems(...) {
    return 0;
}
u32 gActiveScriptInfo(...) {
    return 0;
}
u32 gArea(...) {
    return 0;
}
u32 gAreaMetadata(...) {
    return 0;
}
u32 gAreaRoomHeaders(...) {
    return 0;
}
u32 gAreaRoomMaps(...) {
    return 0;
}
u32 gAreaTable(...) {
    return 0;
}
u32 gAreaTileSets(...) {
    return 0;
}
u32 gAreaTiles(...) {
    return 0;
}
u32 gAuxPlayerEntities(...) {
    return 0;
}
u32 gBG0Buffer(...) {
    return 0;
}
u32 gBG1Buffer(...) {
    return 0;
}
u32 gBG2Buffer(...) {
    return 0;
}
u32 gBG3Buffer(...) {
    return 0;
}
u32 gBgAnimations(...) {
    return 0;
}
u32 gCarriedEntity(...) {
    return 0;
}
u32 gCaveBorderMapData(...) {
    return 0;
}
u32 gChooseFileState(...) {
    return 0;
}
u32 gCollidableCount(...) {
    return 0;
}
u32 gCollisionMtx(...) {
    return 0;
}
u32 gCopyToEndOfEwram_End(...) {
    return 0;
}
u32 gCopyToEndOfEwram_Start(...) {
    return 0;
}
u32 gCurrentRoomMemory(...) {
    return 0;
}
u32 gCurrentRoomProperties(...) {
    return 0;
}
u32 gCurrentWindow(...) {
    return 0;
}
u32 gDiggingCaveEntranceTransition(...) {
    return 0;
}
u32 gDungeonMap(...) {
    return 0;
}
u32 gDungeonNames(...) {
    return 0;
}
u32 gEndOfEwram(...) {
    return 0;
}
u32 gEntCount(...) {
    return 0;
}
u32 gEntities(...) {
    return 0;
}
u32 gEntityLists(...) {
    return 0;
}
u32 gEntityListsBackup(...) {
    return 0;
}
u32 gExitList_RoyalValley_ForestMaze(...) {
    return 0;
}
u32 gExitLists(...) {
    return 0;
}
u32 gExtraFrameOffsets(...) {
    return 0;
}
u32 gFigurines(...) {
    return 0;
}
u32 gFixedTypeGfxData(...) {
    return 0;
}
u32 gFrameObjLists(...) {
    return 0;
}
u32 gFuseInfo(...) {
    return 0;
}
u32 gGFXSlots(...) {
    return 0;
}
u32 gGfxGroups(...) {
    return 0;
}
u32 gGlobalGfxAndPalettes(...) {
    return 0;
}
u32 gHUD(...) {
    return 0;
}
u32 gHitbox_0(...) {
    return 0;
}
u32 gHitbox_1(...) {
    return 0;
}
u32 gHitbox_10(...) {
    return 0;
}
u32 gHitbox_11(...) {
    return 0;
}
u32 gHitbox_12(...) {
    return 0;
}
u32 gHitbox_13(...) {
    return 0;
}
u32 gHitbox_14(...) {
    return 0;
}
u32 gHitbox_15(...) {
    return 0;
}
u32 gHitbox_16(...) {
    return 0;
}
u32 gHitbox_17(...) {
    return 0;
}
u32 gHitbox_18(...) {
    return 0;
}
u32 gHitbox_19(...) {
    return 0;
}
u32 gHitbox_2(...) {
    return 0;
}
u32 gHitbox_20(...) {
    return 0;
}
u32 gHitbox_21(...) {
    return 0;
}
u32 gHitbox_22(...) {
    return 0;
}
u32 gHitbox_23(...) {
    return 0;
}
u32 gHitbox_24(...) {
    return 0;
}
u32 gHitbox_25(...) {
    return 0;
}
u32 gHitbox_26(...) {
    return 0;
}
u32 gHitbox_27(...) {
    return 0;
}
u32 gHitbox_28(...) {
    return 0;
}
u32 gHitbox_29(...) {
    return 0;
}
u32 gHitbox_3(...) {
    return 0;
}
u32 gHitbox_30(...) {
    return 0;
}
u32 gHitbox_31(...) {
    return 0;
}
u32 gHitbox_32(...) {
    return 0;
}
u32 gHitbox_4(...) {
    return 0;
}
u32 gHitbox_5(...) {
    return 0;
}
u32 gHitbox_6(...) {
    return 0;
}
u32 gHitbox_7(...) {
    return 0;
}
u32 gHitbox_8(...) {
    return 0;
}
u32 gHitbox_9(...) {
    return 0;
}
u32 gInput(...) {
    return 0;
}
u32 gInteractableObjects(...) {
    return 0;
}
u32 gIntroState(...) {
    return 0;
}
u32 gLilypadRails(...) {
    return 0;
}
u32 gMPlayInfos(...) {
    return 0;
}
u32 gMPlayInfos2(...) {
    return 0;
}
u32 gMPlayTracks(...) {
    return 0;
}

u32 gManagerCount(...) {
    return 0;
}
u32 gMapActTileToSurfaceType(...) {
    return 0;
}
u32 gMapBottom(...) {
    return 0;
}
u32 gMapData(...) {
    return 0;
}
u32 gMapDataBottomSpecial(...) {
    return 0;
}
u32 gMapDataTopSpecial(...) {
    return 0;
}
u32 gMapTop(...) {
    return 0;
}
u32 gMenu(...) {
    return 0;
}
u32 gMessage(...) {
    return 0;
}
u32 gMessageChoices(...) {
    return 0;
}
u32 gMoreSpritePtrs(...) {
    return 0;
}
u32 gNPCData(...) {
    return 0;
}
u32 gNewWindow(...) {
    return 0;
}
u32 gOverworldLocations(...) {
    return 0;
}
u32 gPaletteBuffer(...) {
    return 0;
}
u32 gPaletteBufferBackup(...) {
    return 0;
}
u32 gPaletteGroups(...) {
    return 0;
}
u32 gPaletteList(...) {
    return 0;
}
u32 gPalette_549(...) {
    return 0;
}
u32 gPauseMenuOptions(...) {
    return 0;
}
u32 gPlayerClones(...) {
    return 0;
}
u32 gPlayerEntity(...) {
    return 0;
}
u32 gPlayerMacroBladeBrothers0(...) {
    return 0;
}
u32 gPlayerMacroBladeBrothers1(...) {
    return 0;
}
u32 gPlayerMacroBladeBrothers2(...) {
    return 0;
}
u32 gPlayerMacroBladeBrothers3(...) {
    return 0;
}
u32 gPlayerMacroBladeBrothers4(...) {
    return 0;
}
u32 gPlayerMacroBladeBrothers5(...) {
    return 0;
}
u32 gPlayerMacroBladeBrothers6(...) {
    return 0;
}
u32 gPlayerMacroBladeBrothers7(...) {
    return 0;
}
u32 gPlayerScriptExecutionContext(...) {
    return 0;
}
u32 gPlayerState(...) {
    return 0;
}
u32 gPossibleInteraction(...) {
    return 0;
}
u32 gPriorityHandler(...) {
    return 0;
}
u32 gRand(...) {
    return 0;
}
u32 gRoomControls(...) {
    return 0;
}
u32 gRoomMemory(...) {
    return 0;
}
u32 gRoomTransition(...) {
    return 0;
}
u32 gRoomVars(...) {
    return 0;
}
u32 gSave(...) {
    return 0;
}
u32 gScriptExecutionContextArray(...) {
    return 0;
}
u32 gShakeOffsets(...) {
    return 0;
}
u32 gSmallChests(...) {
    return 0;
}
u32 gSpriteAnimations_322(...) {
    return 0;
}
u32 gSpriteAnimations_GhostBrothers(...) {
    return 0;
}
u32 gSpritePtrs(...) {
    return 0;
}
u32 gSubtasks(...) {
    return 0;
}
u32 gTextGfxBuffer(...) {
    return 0;
}
u32 gTextRender(...) {
    return 0;
}
u32 gTilesForSpecialTiles(...) {
    return 0;
}
u32 gTranslations(...) {
    return 0;
}
u32 gUI(...) {
    return 0;
}
u32 gUIElementDefinitions(...) {
    return 0;
}
u32 gUnk_03000420(...) {
    return 0;
}
u32 gUnk_03000C30(...) {
    return 0;
}
u32 gUnk_03001020(...) {
    return 0;
}
u32 gUnk_03003C70(...) {
    return 0;
}
u8 gUnk_03003DE0;
u32 gUnk_03003DE4(...) {
    return 0;
}
u32 gUnk_additional_8_DeepwoodShrine_StairsToB1(...) {
    return 0;
}
u32 gUnk_additional_8_HouseInteriors1_Library1F(...) {
    return 0;
}
u32 gUnk_additional_8_HouseInteriors3_BorlovEntrance(...) {
    return 0;
}
u32 gUnk_additional_8_HyruleCastle_3(...) {
    return 0;
}
u32 gUnk_additional_8_MelarisMine_Main(...) {
    return 0;
}
u32 gUnk_additional_8_PalaceOfWinds_GyorgTornado(...) {
    return 0;
}
u32 gUnk_additional_9_HouseInteriors1_Library1F(...) {
    return 0;
}
u32 gUnk_additional_9_HouseInteriors2_Percy(...) {
    return 0;
}
u32 gUnk_additional_9_HouseInteriors3_BorlovEntrance(...) {
    return 0;
}
u32 gUnk_additional_9_MelarisMine_Main(...) {
    return 0;
}
u32 gUnk_additional_9_PalaceOfWinds_GyorgTornado(...) {
    return 0;
}
u32 gUnk_additional_a_CaveOfFlamesBoss_Main(...) {
    return 0;
}
u32 gUnk_additional_a_DeepwoodShrineBoss_Main(...) {
    return 0;
}
u32 gUnk_additional_a_HouseInteriors2_Percy(...) {
    return 0;
}
u32 gUnk_additional_a_HouseInteriors3_BorlovEntrance(...) {
    return 0;
}
u32 gUnk_additional_a_TempleOfDroplets_BigOcto(...) {
    return 0;
}
u32 gUnk_additional_c_HouseInteriors2_Romio(...) {
    return 0;
}
u32 gUpdateContext(...) {
    return 0;
}
u32 gUpdateVisibleTiles(...) {
    return 0;
}
u32 gUsedPalettes(...) {
    return 0;
}
u32 gVBlankDMA(...) {
    return 0;
}
u32 gWallMasterScreenTransitions(...) {
    return 0;
}
u32 gZeldaFollowerText(...) {
    return 0;
}
u32 gzHeap(...) {
    return 0;
}
u32 m4aMPlayAllStop(...) {
    return 0;
}
u32 m4aMPlayImmInit(...) {
    return 0;
}
u32 m4aMPlayTempoControl(...) {
    return 0;
}
u32 m4aMPlayVolumeControl(...) {
    return 0;
}
u32 m4aSongNumStart(...) {
    return 0;
}
u32 m4aSongNumStartOrContinue(...) {
    return 0;
}
u32 m4aSongNumStop(...) {
    return 0;
}
u32 m4aSoundInit(...) {
    return 0;
}
u32 m4aSoundMain(...) {
    return 0;
}
u32 m4aSoundVSync(...) {
    return 0;
}
u32 m4aSoundVSyncOff(...) {
    return 0;
}
u32 m4aSoundVSyncOn(...) {
    return 0;
}
u32 ram_ClearAndUpdateEntities(...) {
    return 0;
}
u32 ram_CollideAll(...) {
    return 0;
}
u32 ram_DrawDirect(...) {
    return 0;
}
u32 ram_DrawEntities(...) {
    return 0;
}
u32 ram_IntrMain(...) {
    return 0;
}
u32 ram_MakeFadeBuff256(...) {
    return 0;
}
u32 ram_UpdateEntities(...) {
    return 0;
}
u32 ram_sub_080ADA04(...) {
    return 0;
}
u32 ram_sub_080B197C(...) {
    return 0;
}
u32 script_08012C48(...) {
    return 0;
}
u32 script_08015B14(...) {
    return 0;
}
u32 script_BedAtSimons(...) {
    return 0;
}
u32 script_BedInLinksRoom(...) {
    return 0;
}
u32 script_BombMinish(...) {
    return 0;
}
u32 script_BombMinishKinstone(...) {
    return 0;
}
u32 script_BusinessScrubIntro(...) {
    return 0;
}
u32 script_CutsceneMiscObjectSwordInChest(...) {
    return 0;
}
u32 script_CutsceneMiscObjectTheLittleHat(...) {
    return 0;
}
u32 script_EzloTalkOcarina(...) {
    return 0;
}
u32 script_ForestMinish1(...) {
    return 0;
}
u32 script_ForestMinish10(...) {
    return 0;
}
u32 script_ForestMinish11(...) {
    return 0;
}
u32 script_ForestMinish12(...) {
    return 0;
}
u32 script_ForestMinish13(...) {
    return 0;
}
u32 script_ForestMinish14(...) {
    return 0;
}
u32 script_ForestMinish15(...) {
    return 0;
}
u32 script_ForestMinish16(...) {
    return 0;
}
u32 script_ForestMinish17(...) {
    return 0;
}
u32 script_ForestMinish18(...) {
    return 0;
}
u32 script_ForestMinish19(...) {
    return 0;
}
u32 script_ForestMinish2(...) {
    return 0;
}
u32 script_ForestMinish20(...) {
    return 0;
}
u32 script_ForestMinish21(...) {
    return 0;
}
u32 script_ForestMinish3(...) {
    return 0;
}
u32 script_ForestMinish4(...) {
    return 0;
}
u32 script_ForestMinish5(...) {
    return 0;
}
u32 script_ForestMinish6(...) {
    return 0;
}
u32 script_ForestMinish7(...) {
    return 0;
}
u32 script_ForestMinish8(...) {
    return 0;
}
u32 script_ForestMinish9(...) {
    return 0;
}
u32 script_MazaalBossObjectMazaal(...) {
    return 0;
}
u32 script_MazaalMacroDefeated(...) {
    return 0;
}
u32 script_MinishVillageObjectLeftStoneOpening(...) {
    return 0;
}
u32 script_MinishVillageObjectRightStoneOpening(...) {
    return 0;
}
u32 script_PlayerAtDarkNut1(...) {
    return 0;
}
u32 script_PlayerAtDarkNut2(...) {
    return 0;
}
u32 script_PlayerAtDarkNut3(...) {
    return 0;
}
u32 script_PlayerAtMadderpillar(...) {
    return 0;
}
u32 script_PlayerGetElement(...) {
    return 0;
}
u32 script_PlayerIntro(...) {
    return 0;
}
u32 script_PlayerSleepingInn(...) {
    return 0;
}
u32 script_PlayerWakeAfterRest(...) {
    return 0;
}
u32 script_PlayerWakingUpAtSimons(...) {
    return 0;
}
u32 script_PlayerWakingUpInHyruleCastle(...) {
    return 0;
}
u32 script_Rem(...) {
    return 0;
}
u32 script_Stockwell(...) {
    return 0;
}
u32 script_StockwellBuy(...) {
    return 0;
}
u32 script_StockwellDogFood(...) {
    return 0;
}
u32 script_TalonGotKey(...) {
    return 0;
}
u32 script_WindTribespeople6(...) {
    return 0;
}
u32 script_ZeldaMagic(...) {
    return 0;
}
u32 sub_08000E44(...) {
    return 0;
}
u32 sub_08000E62(...) {
    return 0;
}
u32 sub_08001290(...) {
    return 0;
}
u32 sub_080012DC(...) {
    return 0;
}
u32 sub_08001318(...) {
    return 0;
}
u32 sub_0800132C(...) {
    return 0;
}
u32 sub_080026C4(...) {
    return 0;
}
u32 sub_080026F2(...) {
    return 0;
}
u32 sub_080028E0(...) {
    return 0;
}
u32 sub_08003FDE(...) {
    return 0;
}
u32 sub_080040A2(...) {
    return 0;
}
u32 sub_080040D8(...) {
    return 0;
}
u32 sub_080040E2(...) {
    return 0;
}
u32 sub_0800417E(...) {
    return 0;
}
u32 sub_0800419C(...) {
    return 0;
}
u32 sub_080041DC(...) {
    return 0;
}
u32 sub_080041E8(...) {
    return 0;
}
u32 sub_08004202(...) {
    return 0;
}
u32 sub_080042BA(...) {
    return 0;
}
u32 sub_080042D0(...) {
    return 0;
}
u32 sub_0800442E(...) {
    return 0;
}
u32 sub_0800445C(...) {
    return 0;
}
u32 sub_080044AE(...) {
    return 0;
}
u32 sub_0800451C(...) {
    return 0;
}
u32 sub_08004542(...) {
    return 0;
}
u32 sub_08004596(...) {
    return 0;
}
u32 sub_080045B4(...) {
    return 0;
}
u32 sub_0800857C(...) {
    return 0;
}
u32 sub_080085B0(...) {
    return 0;
}
u32 sub_080086B4(...) {
    return 0;
}
u32 sub_08008926(...) {
    return 0;
}
u32 sub_08008AA0(...) {
    return 0;
}
u32 sub_08008AC6(...) {
    return 0;
}
u32 sub_080B197C(...) {
    return 0;
}
u32 sub_080B1B84(...) {
    return 0;
}
u32 sub_080B1BA4(...) {
    return 0;
}
